name: Create Release

on:
  push:
    tags:
      - '*/[0-9]+.[0-9]+.[0-9]+'

jobs:
    create-docker-image:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Extract Tag Information
          id: tag_info
          run: echo "TAG=${{ github.ref }}" >> $GITHUB_ENV

        - name: Set Algorithm Name Variable
          id: algorithm
          run: echo "ALGORITHM=$(echo $TAG | cut -d '/' -f 3)" >> $GITHUB_ENV

        - name: Extract Version from Tag
          id: version
          run: echo "VERSION=$(echo $TAG | cut -d '/' -f 4)" >> $GITHUB_ENV

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: harbor2.vantage6.ai
            username: ${{ secrets.STARTER_HARBOR_USER }}
            password: ${{ secrets.STARTER_HARBOR_SECRET }}

        - name: Run Makefile Rule
          run: make $ALGORITHM TAG=$VERSION
